version: '3.9'

services:

  db:
    container_name: db
    network_mode: host
    shm_size: 2g
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  api:
    container_name: api
    build: .
    network_mode: host
    depends_on:
      - db
