# Generated by Django 4.1.4 on 2022-12-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userlinks_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlinks',
            old_name='user_id',
            new_name='user',
        ),
    ]
